name: Docs Index Check

on:
  push:
    branches: [main, develop]
    paths:
      - "docs/**"
      - "scripts/update-docs-index.mjs"
      - "package.json"
  pull_request:
    branches: [main, develop]
    paths:
      - "docs/**"
      - "scripts/update-docs-index.mjs"
      - "package.json"

jobs:
  check-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - name: Rebuild docs index
        run: npm run docs:index
      - name: Fail if index changed
        run: |
          if ! git diff --exit-code -- docs/INDEX.md; then
            echo "docs/INDEX.md is out of date. Run 'npm run docs:index' and commit changes.";
            exit 1;
          fi
